### ISSUE TITLE
Cannot bootstrap SSR app with Jenkins

### ISSUE THREAD

**Issue by estherthetesteramido** [amido/stacks#57]
**Repository the bug was found in**
https://github.com/amido/stacks-webapp-template

**Describe the bug**
When attempting to bootstrap an SSR app with the pipeline as Jenkins, there are no files to copy, as the pipelines either haven't been configured or it errors.

**To Reproduce**
```
npx @amidostacks/scaffolding-cli@1.37.0 run -i
✔ Please provide the company name … derek-rose
✔ Please provide the project name … web-app
✔ Select Project type › React app with server side rendering
✔ Please provide scope (domain) … web-app
✔ Select Pipeline Tool › Jenkins
✔ Select Target Cloud Platform › GKE
✔ Continue to additional project configuration? … yes
✔ Please provide version control repository name … ssr-web-app
✔ Please provide platform service region … europe-west1
✔ Select Terraform remote state storage service? › GCS
✔ Provide host name (DNS domain) … app.derekrose-staging.de-facto.com
```

**Expected behaviour**
SSR template with Jenkins pipeline.

**Screenshots**
```
----> 

Ooooops - Something went wrong 

error: workflows[determinedChoice.toLowerCase(...)] is not a function
TypeError: workflows[determinedChoice.toLowerCase(...)] is not a function
    at selectFlow (/Users/estherlloyd/.npm/_npx/19532/lib/node_modules/@amidostacks/scaffolding-cli/dist/domain/prompt.js:86:73)
    at Object.runCli (/Users/estherlloyd/.npm/_npx/19532/lib/node_modules/@amidostacks/scaffolding-cli/dist/domain/prompt.js:19:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.cliCommand [as handler] (/Users/estherlloyd/.npm/_npx/19532/lib/node_modules/@amidostacks/scaffolding-cli/dist/index.js:42:24) 
 
code: -1 

<----- 


Please raise a bug/issue (​https://github.com/amido/stacks-webapp-template/issues​) if you think it's an issue with the CLI 
```

**Platform (please complete the following information):**
Mac

**Additional context**

**Comment by estherthetesteramido** [comment]
Solved in:
https://github.com/amido/stacks-webapp-template/pull/384
https://github.com/amido/stacks-webapp-template/pull/394
https://github.com/amido/stacks-webapp-template/pull/386
